=== UO301919/SEW/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified" targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitudCircuito" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha" />
				<xs:element ref="horaInicio" />
				<xs:element ref="vueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="patrocinador" />
				<xs:element ref="referencias" />
				<xs:element ref="galeriaFotos" />
				<xs:element ref="galeriaVideos" />
				<xs:element ref="puntoOrigen" />
				<xs:element ref="tramos" />
				<xs:element ref="vencedor" />
				<xs:element ref="clasificacionMundial" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />

	<xs:element name="longitudCircuito">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="longitudCircuitoType">
          <xs:attribute name="unidad" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="metros"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
     </xs:complexType>
    </xs:element>

    <xs:simpleType name="longitudCircuitoType">
     <xs:restriction base="xs:decimal">
       <xs:minExclusive value="0"/>
     </xs:restriction>
    </xs:simpleType>

	<xs:element name="anchura">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="anchuraType">
          <xs:attribute name="unidad" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="metros"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
     </xs:complexType>
    </xs:element>
    <xs:simpleType name="anchuraType">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="5"/>
     </xs:restriction>
    </xs:simpleType>

	<xs:element name="fecha" type="xs:date" />
	<xs:element name="horaInicio" type="xs:time" />

	<xs:element name="vueltas">
		<xs:simpleType>
			<xs:restriction base="xs:positiveInteger"/>
		</xs:simpleType>
	</xs:element>

	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="patrocinador" type="xs:string" />
	
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="src" type="xs:anyURI" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="galeriaFotos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="foto" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="foto">
    <xs:complexType>
      <xs:attribute name="src" type="xs:anyURI" use="required"/>
      <xs:attribute name="alt" type="xs:string"/>
    </xs:complexType>
  </xs:element>

	<xs:element name="galeriaVideos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="video" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="video">
    <xs:complexType>
      <xs:attribute name="src" type="xs:anyURI" use="required"/>
    </xs:complexType>
  </xs:element>

	<xs:element name="puntoOrigen">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="longitudOrigen"/>
        <xs:element ref="latitudOrigen"/>
        <xs:element ref="altitudOrigen"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="longitudOrigen" type="lonType"/>
  <xs:element name="latitudOrigen" type="latType"/>
  <xs:element name="altitudOrigen" type="altType"/>

  <!-- Tipos para coordenadas -->
  <xs:simpleType name="latType">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="-90"/>
      <xs:maxInclusive value="90"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="lonType">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="-180"/>
      <xs:maxInclusive value="180"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="altType">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="tramos">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="tramo" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="tramo">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="distancia"/>
      <xs:element ref="longitud"/>
      <xs:element ref="latitud"/>
      <xs:element ref="altitud"/>
      <xs:element ref="sector"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="distancia">
  <xs:complexType>
    <xs:simpleContent>
      <xs:extension base="distanciaType">
        <xs:attribute name="unidad" use="required">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="metros"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:element>

<xs:simpleType name="distanciaType">
  <xs:restriction base="xs:decimal">
    <xs:minInclusive value="0"/>
  </xs:restriction>
</xs:simpleType>

<xs:element name="latitud" type="latType"/>
<xs:element name="longitud" type="lonType"/>
<xs:element name="altitud" type="altType"/>
	<xs:element name="sector" type="xs:string" />
	<xs:element name="vencedor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="tiempo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="tiempo" type="xs:duration" />
	<xs:element name="clasificacionMundial">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="piloto" />
				<xs:element ref="piloto" />
				<xs:element ref="piloto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="piloto" type="xs:string" />
</xs:schema>

=== UO301919/SEW/MotoGP-Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xmlns="http://www.uniovi.es"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.uniovi.es circuito.xsd">
    <nombre>Balaton Park</nombre>
    <longitudCircuito unidad="metros">4115</longitudCircuito>
    <anchura unidad="metros">13</anchura>
    <fecha>2025-08-24</fecha>
    <horaInicio>14:00:00</horaInicio>
    <vueltas>26</vueltas>
    <localidad>Balatonfőkajár</localidad>
    <pais>Hungría</pais>
    <patrocinador>Monster Energy</patrocinador>

    <referencias>
        <referencia src="https://www.balatonparkcircuit.com">Sitio oficial Balaton Park</referencia>
        <referencia src="https://es.wikipedia.org/wiki/Circuito_de_Balaton_Park">Wikipedia Balaton Park</referencia>
        <referencia src="https://www.racingcircuits.info/europe/hungary/balaton-park.html#map_2025todate_2">Racing circuits hungría</referencia>
    </referencias>

    <galeriaFotos>
        <foto src="multimedia/Panoramica.jpg" alt="Vista panorámica del circuito"/>
        <foto src="multimedia/MapaTec.jpg" alt="Mapa técnico del circuito"/>
    </galeriaFotos>

    <galeriaVideos>
        <video src="multimedia/BalatonCorto.mp4"/>
    </galeriaVideos>

    <puntoOrigen>
        <longitudOrigen>18.200872</longitudOrigen>
        <latitudOrigen>47.007255</latitudOrigen>
        <altitudOrigen>108</altitudOrigen>
    </puntoOrigen>

    <tramos>
        <tramo>
            <distancia unidad="metros">36.6</distancia>
            <longitud>18.19898</longitud>
            <latitud>47.004687</latitud>
            <altitud>111</altitud>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">21</distancia>
            <longitud>18.19867</longitud>
            <latitud>47.004635</latitud>
            <altitud>112</altitud>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">89.6</distancia>
            <longitud>18.198488</longitud>
            <latitud>47.004723</latitud>
            <altitud>112</altitud>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">25</distancia>
            <longitud>18.198404</longitud>
            <latitud>47.005525</latitud>
            <altitud>110</altitud>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">22</distancia>
            <longitud>18.198253</longitud>
            <latitud>47.005726</latitud>
            <altitud>111</altitud>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">30.6</distancia>
            <longitud>18.198002</longitud>
            <latitud>47.005788</latitud>
            <altitud>111</altitud>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">66</distancia>
            <longitud>18.197729</longitud>
            <latitud>47.005747</latitud>
            <altitud>112</altitud>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">23</distancia>
            <longitud>18.197213</longitud>
            <latitud>47.005111</latitud>
            <altitud>110</altitud>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">30.5</distancia>
            <longitud>18.197153</longitud>
            <latitud>47.004904</latitud>
            <altitud>110</altitud>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">120</distancia>
            <longitud>18.197175</longitud>
            <latitud>47.004630</latitud>
            <altitud>111</altitud>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">25</distancia>
            <longitud>18.198260</longitud>
            <latitud>47.003631</latitud>
            <altitud>111</altitud>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">40</distancia>
            <longitud>18.198571</longitud>
            <latitud>47.003559</latitud>
            <altitud>110</altitud>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">45</distancia>
            <longitud>18.199011</longitud>
            <latitud>47.003585</latitud>
            <altitud>110</altitud>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">330</distancia>
            <longitud>18.199391</longitud>
            <latitud>47.003766</latitud>
            <altitud>110</altitud>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">590</distancia>
            <longitud>18.202918</longitud>
            <latitud>47.008437</latitud>
            <altitud>110</altitud>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">9</distancia>
            <longitud>18.203015</longitud>
            <latitud>47.008483</latitud>
            <altitud>110</altitud>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">14</distancia>
            <longitud>18.203194</longitud>
            <latitud>47.008502</latitud>
            <altitud>109</altitud>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">14</distancia>
            <longitud>18.203363</longitud>
            <latitud>47.008448</latitud>
            <altitud>109</altitud>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">70</distancia>
            <longitud>18.204004</longitud>
            <latitud>47.007991</latitud>
            <altitud>110</altitud>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">18</distancia>
            <longitud>18.204254</longitud>
            <latitud>47.007971</latitud>
            <altitud>110</altitud>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">130</distancia>
            <longitud>18.205956</longitud>
            <latitud>47.008106</latitud>
            <altitud>109</altitud>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">30</distancia>
            <longitud>18.206362</longitud>
            <latitud>47.008048</latitud>
            <altitud>108</altitud>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">34</distancia>
            <longitud>18.206770</longitud>
            <latitud>47.007931</latitud>
            <altitud>108</altitud>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">27</distancia>
            <longitud>18.207070</longitud>
            <latitud>47.007791</latitud>
            <altitud>108</altitud>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">60</distancia>
            <longitud>18.207547</longitud>
            <latitud>47.007396</latitud>
            <altitud>107</altitud>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">410</distancia>
            <longitud>18.208979</longitud>
            <latitud>47.003939</latitud>
            <altitud>112</altitud>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">20</distancia>
            <longitud>18.209212</longitud>
            <latitud>47.003827</latitud>
            <altitud>112</altitud>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">27</distancia>
            <longitud>18.209549</longitud>
            <latitud>47.003854</latitud>
            <altitud>111</altitud>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">15</distancia>
            <longitud>18.209712</longitud>
            <latitud>47.003783</latitud>
            <altitud>111</altitud>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">145</distancia>
            <longitud>18.210073</longitud>
            <latitud>47.002534</latitud>
            <altitud>110</altitud>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">30</distancia>
            <longitud>18.210447</longitud>
            <latitud>47.002432</latitud>
            <altitud>111</altitud>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">20</distancia>
            <longitud>18.210700</longitud>
            <latitud>47.002500</latitud>
            <altitud>110</altitud>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">30</distancia>
            <longitud>18.210853</longitud>
            <latitud>47.002734</latitud>
            <altitud>108</altitud>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">360</distancia>
            <longitud>18.209865</longitud>
            <latitud>47.005804</latitud>
            <altitud>110</altitud>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidad="metros">110</distancia>
            <longitud>18.209302</longitud>
            <latitud>47.006773</latitud>
            <altitud>108</altitud>
